import type { NextPage } from "next";
import Head from "next/head";
import { Center, Heading, Stack } from "@chakra-ui/react";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <Center px={8} py={24}>
        <Stack spacing={2}>
          <Heading as="h1" size="2xl">
            LNURL Pay ⚡️
          </Heading>

          <Heading size="md" color="gray.300">
            Convert an LNURL or Lightning Address to a BOLT11 invoice.
          </Heading>
        </Stack>
      </Center>
    </div>
  );
};

export default Home;
